import {
  Activity,
  BarChart3,
  Binary,
  BookOpen,
  Boxes,
  CheckSquare,
  ClipboardList,
  Compass,
  Gauge,
  GitBranch,
  GitPullRequest,
  Layers,
  LineChart,
  ListTree,
  Network,
  Radar,
  ScanLine,
  SquareCode,
  Route,
  Workflow,
  SlidersHorizontal,
  MousePointer2,
  FolderSearch,
  FolderTree,
  Wand2,
} from 'lucide-react';

export const navSections = [
  {
    label: 'Analyze',
    items: [
      { to: '/', label: 'Overview', icon: Gauge },
      { to: '/simulator', label: 'RenderFlow Simulator', icon: Network },
      { to: '/project-analyzer', label: 'Project Analyzer', icon: FolderSearch },
      { to: '/folder-compare', label: 'Folder Compare', icon: FolderTree },
      { to: '/code-refactor-studio', label: 'Code Refactor Studio', icon: Wand2 },
      { to: '/architecture-workbench', label: 'Architecture Workbench', icon: MousePointer2 },
      { to: '/what-if-studio', label: 'What If Studio', icon: SlidersHorizontal },
      { to: '/before-after', label: 'Before vs After', icon: ScanLine },
      { to: '/performance-timeline', label: 'Performance Timeline', icon: Activity },
      { to: '/profiler', label: 'Profiler Flamegraph', icon: Radar },
      { to: '/architecture-score', label: 'Architecture Score', icon: LineChart },
      { to: '/export-report', label: 'Export Report', icon: ClipboardList },
    ],
  },
  {
    label: 'Labs',
    items: [
      { to: '/state-ownership', label: 'State Ownership', icon: Boxes },
      { to: '/prop-flow', label: 'Prop Flow', icon: GitBranch },
      { to: '/context-update', label: 'Context Update', icon: Route },
      { to: '/memoization', label: 'Memoization', icon: Binary },
      { to: '/list-rendering', label: 'List Rendering', icon: ListTree },
      { to: '/dashboard-demo', label: 'Dashboard Demo', icon: BarChart3 },
      { to: '/scenario-builder', label: 'Scenario Builder', icon: Workflow },
      { to: '/jsx-import', label: 'JSX Import', icon: SquareCode },
    ],
  },
  {
    label: 'Reference',
    items: [
      { to: '/advisor-suite', label: 'Advisor Suite', icon: Compass },
      { to: '/learning-missions', label: 'Learning Missions', icon: GitPullRequest },
      { to: '/anti-patterns', label: 'Anti-Patterns', icon: Layers },
      { to: '/final-checklist', label: 'Final Checklist', icon: CheckSquare },
      { to: '/guide', label: 'How to Use', icon: BookOpen },
    ],
  },
];

export const navItems = navSections.flatMap((section) => section.items);
